name: Maven Build

# Run workflow for any push to a branch
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  workflow_dispatch:

# Only permit one build per branch/tag
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: ${{ !contains(github.ref_name, 'release/') }}

jobs:
  maven-build:
    uses: Telicent-oss/shared-workflows/.github/workflows/maven.yml@main
    with:
      # Some Docker based tests in this repository but should be fine to pull the images we need without login
      USES_DOCKERHUB_IMAGES: false
      # Want SNAPSHOTs to be published from main
      PUBLISH_SNAPSHOTS: true
      MAIN_BRANCH: main
      # If running in debug mode, use appropriate logging
      MAVEN_DEBUG_ARGS: -Dlogback.configurationFile=logback-debug.xml
      JAVA_VERSION: 21
    secrets: inherit 

  docker-build:
    needs: maven-build
    uses: telicent-oss/shared-workflows/.github/workflows/docker-push-to-registries.yml@main
    with:
      APP_NAME: smart-cache-debug-tools
      APP_NAME_PREFIX: ""
      PATH: .
      DOCKERFILE: docker/Dockerfile
      VERSION: ${{ needs.maven-build.outputs.version }}
      TARGET: smart-cache-debug-tools
      BUILD_ARGS: |
        PROJECT_VERSION=${{ needs.maven-build.outputs.version }}
      USES_MAVEN: true
      JAVA_VERSION: 21
    secrets: inherit



